name: Deploy to S3 + CloudFront

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build


      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::942198061038:role/github-actions-menu-digital-deploy
          aws-region: us-east-1

      - name: Sync to S3
        run: aws s3 sync dist/menu-digital/browser s3://aws-bucket-manuespo --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E1JNQE0T485H8D --paths "/*"